
CREATE TABLE VES.SV_CAMPCUR
(	COD_CAMP NUMBER(5,0),
     COD_VEST NUMBER(3,0),
     COD_CURS VARCHAR2(8 ),
     SIT_CADA NUMBER(1,0),
     ID NUMBER,
     TX_DESC NUMBER(7,4) DEFAULT 0,
     VL_MATRIC NUMBER(9,2),
     DATA_CAD TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
     NOME_USU_CAD VARCHAR2(20 ) DEFAULT NULL,
     DATA_MOD DATE DEFAULT NULL,
     NOME_USU_MOD VARCHAR2(20 ) DEFAULT NULL,
     TX_DESC_SEG NUMBER(7,4)
) ;


GRANT DELETE ON VES.SV_CAMPCUR TO sa;
GRANT INSERT ON VES.SV_CAMPCUR TO sa;
GRANT SELECT ON VES.SV_CAMPCUR TO sa;
GRANT UPDATE ON VES.SV_CAMPCUR TO sa;