
CREATE TABLE ACD.PAIS
(	COD_PAIS NUMBER(3,0),
     NOME_PAIS VARCHAR2(50 ),
     ABR_PAIS VARCHAR2(10 ),
     OBS_AUDIT VARCHAR2(500 ),
     NACIONAL VARCHAR2(30 ),
     NM_DOC_ID VARCHAR2(20 ),
     NACIONALIDADE_MASCULINO VARCHAR2(80 ),
     NACIONALIDADE_FEMININO VARCHAR2(80 ),
     PREPOSICAO VARCHAR2(10 )
) ;
