
CREATE TABLE VES.SV_CAMCUPOM
(	ID_CUPOM NUMBER(8,0),
     COD_CAMP NUMBER(5,0),
     NOME_USU VARCHAR2(20 ),
     DATA_CAD DATE
) ;
GRANT DELETE ON VES.SV_CAMCUPOM TO sa;
GRANT INSERT ON VES.SV_CAMCUPOM TO sa;
GRANT SELECT ON VES.SV_CAMCUPOM TO sa;
GRANT UPDATE ON VES.SV_CAMCUPOM TO sa;