-- VES.SV_CONVEMP definition

CREATE TABLE VES.SV_CONVEMP
(	ID_CONVENIO NUMBER(4,0),
     COD_EMPR NUMBER(3,0),
     SIT_CADA NUMBER(1,0),
     COD_CAMP NUMBER(5,0),
     ID_CONVEMP NUMBER(15,0)
) ;
GRANT DELETE ON VES.SV_CONVEMP TO sa;
GRANT INSERT ON VES.SV_CONVEMP TO sa;
GRANT SELECT ON VES.SV_CONVEMP TO sa;
GRANT UPDATE ON VES.SV_CONVEMP TO sa;