
CREATE TABLE VES.SV_COTA_CAMP
(	ID_SV_COTA_CAMP NUMBER(8,0),
     COD_CAMP NUMBER(5,0),
     ANO_VEST NUMBER(4,0),
     SEM_VEST NUMBER(1,0),
     QTDE_COTAS NUMBER(8,0),
     OBSERVAC VARCHAR2(500 ),
     DATA_CAD DATE,
     NOME_USU VARCHAR2(20 ),
     SIT_PARAM NUMBER(1,0)
) ;


GRANT DELETE ON VES.SV_COTA_CAMP TO sa;
GRANT INSERT ON VES.SV_COTA_CAMP TO sa;
GRANT SELECT ON VES.SV_COTA_CAMP TO sa;
GRANT UPDATE ON VES.SV_COTA_CAMP TO sa;
