CREATE TABLE VES.SV_CONVENIO
(	ID_CONVENIO NUMBER(4,0),
     DES_CONV VARCHAR2(150 ),
     NOME_EMP VARCHAR2(100 ),
     COD_SDES NUMBER(4,0),
     NOME_CON VARCHAR2(100 ),
     FONE_CON VARCHAR2(50 ),
     DATA_CAD DATE,
     NOME_USU VARCHAR2(20 ),
     OBSERVAC VARCHAR2(300 ),
     SIT_CADA NUMBER(1,0),
     E_MAIL VARCHAR2(120 ),
     INSTITUICAO VARCHAR2(120 ),
     CAMPANHA VARCHAR2(120 ),
     ANALISTA VARCHAR2(120 ),
     STATUS_INTEGRACAO NUMBER(2,0) DEFAULT 0,
     TIPO_CONVENIO NUMBER DEFAULT 0
) ;

GRANT DELETE ON VES.SV_CONVENIO TO sa;
GRANT INSERT ON VES.SV_CONVENIO TO sa;
GRANT SELECT ON VES.SV_CONVENIO TO sa;
GRANT UPDATE ON VES.SV_CONVENIO TO sa;